export const homeObjOne = {
    id: 'startup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Startup company',
    headline: 'Unlimited and global funding',
    description: 'Get funds for your Startup in a smart, transparent and decentralized way',
    buttonLabel: 'Get started',
    imgStart: false,
    img: 'images/svg-f.svg',
    alt: 'Startup',
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjTwo = {
    id: 'realEstate',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Real Estate',
    headline: 'Innovative and alternative sources of financing',
    description: 'Finances your projects democratically and transparently through tokenization',
    buttonLabel: 'Get started',
    imgStart: true,
    img: 'images/svg-2.svg',
    alt: 'Startup',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjThree = {
    id: 'environment',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Environment',
    headline: 'Financing in environmental projects',
    description: 'We create Tokens backed by the impact of your Project',
    buttonLabel: 'Get started',
    imgStart: false,
    img: 'images/svg-h.svg',
    alt: 'Startup',
    dark: false,
    primary: false,
    darkText: true,
};