export const homeObjOne = {
    id: 'startup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Startup',
    headline: 'Unlimited and global funding',
    description: 'We are a leading provider of utility tokens, with a focus on creating innovative and user-friendly products that deliver real value to our customers. Our team of experts has a deep understanding of blockchain technology and a track record of success in the utility token space.',
    buttonLabel: 'Get started',
    imgStart: false,
    img: 'images/svg-f.svg',
    alt: 'Startup',
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjTwo = {
    id: 'realEstate',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Real Estate',
    headline: 'Alternative sources of financing',
    description: 'We are dedicated to delivering the highest quality service and the best possible results for our clients. Contact us today to learn more about how we can help you harness the power of utility tokens to drive growth and success.',
    buttonLabel: 'Get started',
    imgStart: true,
    img: 'images/svg-2.svg',
    alt: 'Startup',
    dark: true,
    primary: true,
    darkText: false,
};

export const homeObjThree = {
    id: 'environment',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Environment',
    headline: 'Financing in environmental projects',
    description: 'Utility tokens are a powerful tool for businesses and organizations, offering a range of benefits including access to products and services, discounts, rewards, and more. Our team can help you design and launch a custom utility token that meets your specific needs and goals, whether you are looking to monetize your products or services, build a loyal customer base, or incentivize certain behaviors.',
    buttonLabel: 'Get started',
    imgStart: false,
    img: 'images/svg-h.svg',
    alt: 'Startup',
    dark: false,
    primary: false,
    darkText: true,
};

export const homeObjFour = {
    id: 'social',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Social Token',
    headline: 'Monetize your brand',
    description: 'A social token is a type of cryptocurrency used to monetize a brand. They can be personal or community tokens. The value of a social token revolves around the brand issuing it, and are used by holders as a way to feel belonging to a certain group.',
    buttonLabel: 'Get started',
    imgStart: true,
    img: 'images/svg-4.svg',
    alt: 'Startup',
    dark: true,
    primary: true,
    darkText: false,
};